package com.example.serbisyofullstack.mapper;

import com.example.serbisyofullstack.dto.nested.PayoutDto;
import com.example.serbisyofullstack.model.entity.Payout;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Maps {@link Payout} to {@link PayoutDto}. Payouts are generated by the payout
 * cycle, so only entity-to-DTO mapping exists.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface PayoutMapper {

    @Mapping(source = "payoutId", target = "id")
    @Mapping(source = "provider.providerProfileId", target = "providerId")
    @Mapping(target = "periodStart", expression = "java(toDateTime(entity.getPeriodStart()))")
    @Mapping(target = "periodEnd", expression = "java(toDateTime(entity.getPeriodEnd()))")
    PayoutDto toDto(Payout entity);

    default LocalDateTime toDateTime(LocalDate date) {
        return date != null ? date.atStartOfDay() : null;
    }
}
